### PR TITLE
Added condition to check wheather all sums are power of 2

### PR DESCRIPTION
**Pull request by Akshayaap**

### CODE REVIEW

**Review by SKR301 — CHANGES_REQUESTED** [review]
Please remove `if (count == 6) {` condition.
I want all outputs not just single!

**Comment by Akshayaap** [comment]
- That's the literally change ¯\_(ツ)_/¯.

**Comment by Akshayaap** [comment]
> I want all answers

- those are not answers,
- a valid answer is answer which have 6 pairs power of 2 (according the definition of problem).

**Comment by Akshayaap** [comment]
- just why😂.

**Comment by SKR301** [comment]
1. This PR was important
2. I requested some changes from you because those changes were required to collect the data I need.
3. You closed the PR so I took it in my hands :smile:

**Comment by Akshayaap** [comment]
> those changes were required to collect the data I need

Huhh... ?

**Pull request merged**
